# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(410, 407)
        self.label_3 = QtWidgets.QLabel(Menu)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_WK = QtWidgets.QPushButton(Menu)
        self.pushButton_WK.setGeometry(QtCore.QRect(140, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_WK.setFont(font)
        self.pushButton_WK.setObjectName("pushButton_WK")
        self.pushButton_SM2_2 = QtWidgets.QPushButton(Menu)
        self.pushButton_SM2_2.setGeometry(QtCore.QRect(140, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_SM2_2.setFont(font)
        self.pushButton_SM2_2.setObjectName("pushButton_SM2_2")
        self.pushButton_SM4D = QtWidgets.QPushButton(Menu)
        self.pushButton_SM4D.setGeometry(QtCore.QRect(140, 310, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_SM4D.setFont(font)
        self.pushButton_SM4D.setObjectName("pushButton_SM4D")
        self.pushButton_SM4E = QtWidgets.QPushButton(Menu)
        self.pushButton_SM4E.setGeometry(QtCore.QRect(140, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_SM4E.setFont(font)
        self.pushButton_SM4E.setObjectName("pushButton_SM4E")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu","Menu"))
        self.label_3.setText(_translate("Menu", "******菜单******"))
        self.pushButton_WK.setText(_translate("Menu", "密钥注充"))
        self.pushButton_SM2_2.setText(_translate("Menu", "SM2测试"))
        self.pushButton_SM4D.setText(_translate("Menu", "SM4解密"))
        self.pushButton_SM4E.setText(_translate("Menu", "SM4加密"))
