# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\SM2En.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 60, 701, 101))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(140, 490, 171, 51))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_return = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_return.setGeometry(QtCore.QRect(500, 490, 171, 51))
        self.pushButton_return.setObjectName("pushButton_return")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 72, 21))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(90, 320, 51, 16))
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 350, 701, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_datalen = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_datalen.setGeometry(QtCore.QRect(210, 280, 131, 31))
        self.textBrowser_datalen.setObjectName("textBrowser_datalen")
        self.textBrowser_mode = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_mode.setGeometry(QtCore.QRect(50, 280, 131, 31))
        self.textBrowser_mode.setObjectName("textBrowser_mode")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 320, 72, 15))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 430, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 210, 111, 31))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SM2加密"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "请在此输入明文"))
        self.pushButton_start.setText(_translate("MainWindow", "加密"))
        self.pushButton_return.setText(_translate("MainWindow", "返回"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">明文：</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "算法"))
        self.label.setText(_translate("MainWindow", "数据长度"))
        self.label_6.setText(_translate("MainWindow", "密文"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">返回数据帧：</span></p></body></html>"))
