# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\SM4De.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 607)
        MainWindow.setWindowIcon(QtGui.QIcon("C:/Users/young/PycharmProjects/myuart/src/3.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_return = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_return.setGeometry(QtCore.QRect(500, 500, 171, 51))
        self.pushButton_return.setObjectName("pushButton_return")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(140, 500, 171, 51))
        self.pushButton_start.setObjectName("pushButton_start")
        self.plainTextEdit_handle = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_handle.setGeometry(QtCore.QRect(50, 140, 701, 41))
        self.plainTextEdit_handle.setObjectName("plainTextEdit_handle")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(360, 440, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 120, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 30, 72, 15))
        self.label_7.setObjectName("label_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 350, 701, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 50, 701, 61))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 220, 191, 31))
        self.label_10.setObjectName("label_10")
        self.textBrowser_mode = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_mode.setGeometry(QtCore.QRect(50, 270, 131, 41))
        self.textBrowser_mode.setObjectName("textBrowser_mode")
        self.textBrowser_datalen = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_datalen.setGeometry(QtCore.QRect(210, 270, 131, 41))
        self.textBrowser_datalen.setObjectName("textBrowser_datalen")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 320, 72, 15))
        self.label.setObjectName("label")
        self.textBrowser_handle = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_handle.setGeometry(QtCore.QRect(370, 270, 121, 41))
        self.textBrowser_handle.setObjectName("textBrowser_handle")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(410, 320, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(90, 320, 41, 20))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SM4解密"))
        self.pushButton_return.setText(_translate("MainWindow", "返回"))
        self.pushButton_start.setText(_translate("MainWindow", "解密"))
        self.plainTextEdit_handle.setPlaceholderText(_translate("MainWindow", "请输入8位16进制句柄"))
        self.label_9.setText(_translate("MainWindow", "明文"))
        self.label_8.setText(_translate("MainWindow", "句柄："))
        self.label_7.setText(_translate("MainWindow", "密文："))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "请在此输入待解密密文"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">返回数据帧：</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "数据长度"))
        self.label_11.setText(_translate("MainWindow", "句柄"))
        self.label_12.setText(_translate("MainWindow", "算法"))
