# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\SM4De.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_return = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_return.setGeometry(QtCore.QRect(500, 490, 171, 51))
        self.pushButton_return.setObjectName("pushButton_return")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(140, 490, 171, 51))
        self.pushButton_start.setObjectName("pushButton_start")
        self.plainTextEdit_handle = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_handle.setGeometry(QtCore.QRect(50, 210, 701, 31))
        self.plainTextEdit_handle.setObjectName("plainTextEdit_handle")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 270, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 190, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 30, 72, 15))
        self.label_7.setObjectName("label_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 300, 701, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 50, 701, 101))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SM4解密"))
        self.pushButton_return.setText(_translate("MainWindow", "返回"))
        self.pushButton_start.setText(_translate("MainWindow", "解密"))
        self.plainTextEdit_handle.setPlaceholderText(_translate("MainWindow", "请输入8位16进制句柄"))
        self.label_9.setText(_translate("MainWindow", "明文："))
        self.label_8.setText(_translate("MainWindow", "句柄："))
        self.label_7.setText(_translate("MainWindow", "密文："))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "请在此输入待解密密文"))
