# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\sm4En.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(360, 410, 91, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_return = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_return.setGeometry(QtCore.QRect(500, 490, 171, 51))
        self.pushButton_return.setObjectName("pushButton_return")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(140, 490, 171, 51))
        self.pushButton_start.setObjectName("pushButton_start")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 330, 701, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 50, 701, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 300, 91, 16))
        self.label_7.setObjectName("label_7")
        self.textBrowser_handle = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_handle.setGeometry(QtCore.QRect(370, 260, 121, 31))
        self.textBrowser_handle.setObjectName("textBrowser_handle")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 190, 111, 31))
        self.label_8.setObjectName("label_8")
        self.textBrowser_mode = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_mode.setGeometry(QtCore.QRect(50, 260, 131, 31))
        self.textBrowser_mode.setObjectName("textBrowser_mode")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(90, 300, 51, 16))
        self.label_9.setObjectName("label_9")
        self.textBrowser_datalen = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_datalen.setGeometry(QtCore.QRect(210, 260, 131, 31))
        self.textBrowser_datalen.setObjectName("textBrowser_datalen")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 300, 72, 15))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SM4加密"))
        self.label_5.setText(_translate("MainWindow", "明文："))
        self.label_6.setText(_translate("MainWindow", "密文"))
        self.pushButton_return.setText(_translate("MainWindow", "返回"))
        self.pushButton_start.setText(_translate("MainWindow", "加密"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "请在此输入待加密明文"))
        self.label_7.setText(_translate("MainWindow", "句柄"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">返回数据帧：</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "算法"))
        self.label.setText(_translate("MainWindow", "数据长度"))
