# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Dell\Desktop\Tiny-Uart\src\tiny_uart.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(730, 550)
        MainWindow.setMinimumSize(QtCore.QSize(730, 550))
        MainWindow.setMaximumSize(QtCore.QSize(730, 560))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/1.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.9)
        MainWindow.setWhatsThis("")
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(570, 10, 151, 223))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.comboBox_uart = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_uart.setGeometry(QtCore.QRect(0, 20, 151, 21))
        self.comboBox_uart.setObjectName("comboBox_uart")
        self.pushButton_open = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_open.setGeometry(QtCore.QRect(0, 160, 151, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setObjectName("pushButton_open")
        self.pushButton_refresh = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_refresh.setGeometry(QtCore.QRect(0, 190, 151, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButton_refresh.setFont(font)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 50, 151, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_baud = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_baud)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_data = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_data.setObjectName("comboBox_data")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_data)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_check = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_check.setObjectName("comboBox_check")
        self.comboBox_check.addItem("")
        self.comboBox_check.addItem("")
        self.comboBox_check.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_check)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_stop = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_stop.setObjectName("comboBox_stop")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_stop)
        self.rx_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.rx_textBrowser.setGeometry(QtCore.QRect(10, 10, 551, 361))
        self.rx_textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
        "color: rgb(0, 255, 0);\n"
        "border-top:1px solid gray;\n"
        "border-bottom:1px solid gray;\n"
        "border-left:1px solid graye;\n"
        "border-right:1px solid gray;\n"
        "border-radius:10px;")
        self.rx_textBrowser.setObjectName("rx_textBrowser")
        self.pushButton_send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_send.setGeometry(QtCore.QRect(570, 410, 91, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
        "border-bottom:1px solid gray;\n"
        "border-left:1px solid graye;\n"
        "border-right:1px solid gray;\n"
        "border-radius:10px; } \n"
        "QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
        "QPushButton:pressed { background-color: rgb(0, 170, 255);}")
        self.pushButton_send.setObjectName("pushButton_send")
        self.pushButton_clear_tx = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_tx.setGeometry(QtCore.QRect(670, 410, 51, 51))
        self.pushButton_clear_tx.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
        "border-bottom:1px solid gray;\n"
        "border-left:1px solid graye;\n"
        "border-right:1px solid gray;\n"
        "border-radius:10px; } \n"
        "QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
        "QPushButton:pressed { background-color: rgb(0, 170, 255);}")
        self.pushButton_clear_tx.setObjectName("pushButton_clear_tx")
        self.pushButton_clear_rx = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_rx.setGeometry(QtCore.QRect(570, 330, 151, 41))
        self.pushButton_clear_rx.setAutoFillBackground(False)
        self.pushButton_clear_rx.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
        "border-bottom:1px solid gray;\n"
        "border-left:1px solid graye;\n"
        "border-right:1px solid gray;\n"
        "border-radius:10px; } \n"
        "QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
        "QPushButton:pressed { background-color: rgb(0, 170, 255);}\n"
        "\n"
        "")
        self.pushButton_clear_rx.setCheckable(False)
        self.pushButton_clear_rx.setAutoDefault(False)
        self.pushButton_clear_rx.setDefault(False)
        self.pushButton_clear_rx.setObjectName("pushButton_clear_rx")
        self.tx_plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tx_plainTextEdit.setGeometry(QtCore.QRect(10, 400, 551, 141))
        self.tx_plainTextEdit.setStyleSheet("")
        self.tx_plainTextEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tx_plainTextEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tx_plainTextEdit.setObjectName("tx_plainTextEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 240, 151, 51))
        self.groupBox_2.setStyleSheet("border-top:1px solid gray;\n"
        "border-bottom:1px solid gray;\n"
        "border-left:1px solid graye;\n"
        "border-right:1px solid gray;\n"
        "border-radius:10px;")
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_ascii = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ascii.setGeometry(QtCore.QRect(0, 20, 67, 19))
        self.radioButton_ascii.setStyleSheet("border:none;")
        self.radioButton_ascii.setChecked(True)
        self.radioButton_ascii.setAutoRepeat(False)
        self.radioButton_ascii.setObjectName("radioButton_ascii")
        self.radioButton_hex = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_hex.setGeometry(QtCore.QRect(80, 20, 51, 19))
        self.radioButton_hex.setMouseTracking(False)
        self.radioButton_hex.setStyleSheet("border:none;")
        self.radioButton_hex.setChecked(False)
        self.radioButton_hex.setObjectName("radioButton_hex")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(570, 480, 151, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.tx_lcdNumber = QtWidgets.QLCDNumber(self.formLayoutWidget_2)
        self.tx_lcdNumber.setStyleSheet("border-top:1px solid gray;\n"
        "border-bottom:1px solid gray;\n"
        "border-left:1px solid graye;\n"
        "border-right:1px solid gray;\n"
        "")
        self.tx_lcdNumber.setProperty("value", 0.0)
        self.tx_lcdNumber.setProperty("intValue", 0)
        self.tx_lcdNumber.setObjectName("tx_lcdNumber")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tx_lcdNumber)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.rx_lcdNumber = QtWidgets.QLCDNumber(self.formLayoutWidget_2)
        self.rx_lcdNumber.setStyleSheet("border-top:1px solid gray;\n"
        "border-bottom:1px solid gray;\n"
        "border-left:1px solid graye;\n"
        "border-right:1px solid gray;\n"
        "")
        self.rx_lcdNumber.setObjectName("rx_lcdNumber")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rx_lcdNumber)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tiny Uart V1.0.0"))
        self.groupBox.setTitle(_translate("MainWindow", "串口选择"))
        self.pushButton_open.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_refresh.setText(_translate("MainWindow", "刷新串口"))
        self.label_4.setText(_translate("MainWindow", "波特率"))
        self.comboBox_baud.setCurrentText(_translate("MainWindow", "4800"))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "4800"))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "115200"))
        self.label.setText(_translate("MainWindow", "数据位"))
        self.comboBox_data.setItemText(0, _translate("MainWindow", "8"))
        self.comboBox_data.setItemText(1, _translate("MainWindow", "7"))
        self.comboBox_data.setItemText(2, _translate("MainWindow", "6"))
        self.comboBox_data.setItemText(3, _translate("MainWindow", "5"))
        self.label_3.setText(_translate("MainWindow", "校验位"))
        self.comboBox_check.setItemText(0, _translate("MainWindow", "N"))
        self.comboBox_check.setItemText(1, _translate("MainWindow", "O"))
        self.comboBox_check.setItemText(2, _translate("MainWindow", "E"))
        self.label_5.setText(_translate("MainWindow", "停止位"))
        self.comboBox_stop.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_stop.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_stop.setItemText(2, _translate("MainWindow", "2"))
        self.rx_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_send.setText(_translate("MainWindow", "发送"))
        self.pushButton_clear_tx.setText(_translate("MainWindow", "清空\n"
"发送"))
        self.pushButton_clear_rx.setText(_translate("MainWindow", "清空接收"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收格式"))
        self.radioButton_ascii.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_hex.setText(_translate("MainWindow", "HEX"))
        self.label_6.setText(_translate("MainWindow", "RX:"))
        self.label_2.setText(_translate("MainWindow", "TX:"))
import ico_rc
